---
title: "neuropil summary"
author: "david"
date: "03/05/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(car)
neuropil = read.csv("C:/Users/BioCraze/Documents/Ruthazer lab/glia_training/summaries/glia training neuropil response summary.csv")
df = data.frame(neuropil)

area <- aov(unlist(df['corrected.area']) ~ unlist(df['treatment']) * unlist(df["time.group"]) )

summary(area)

shapiro.test(area$residuals)

leveneTest(unlist(df['corrected.area']) ~ unlist(df['treatment']) * unlist(df["time.group"]))

#not normal or equal variances

shap_area = kruskal.test(unlist(df['corrected.area']) ~ unlist(df['treatment']):unlist(df['time.group']))

shap_area
#significant diff in treatments and time groups therefore we will report parametric results

TukeyHSD(area)
```



```{r}
peak <- aov(unlist(df['corrected.peaks']) ~ unlist(df['treatment']) * unlist(df["time.group"]) )

summary(peak)

shapiro.test(area$residuals)

leveneTest(unlist(df['corrected.peaks']) ~ unlist(df['treatment']) * unlist(df["time.group"]))

#not normal or equal variances

shap_peak = kruskal.test(unlist(df['corrected.peaks']) ~ unlist(df['time.group']))

shap_peak
#significant diff in treatments and time groups therefore we will report parametric results

TukeyHSD(peak)
```

